language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo

script:
  - cd serde_dyn
  - cargo build --verbose --all
  - cargo test --verbose --all
  - cd ../uuid_gen
  - cargo build --verbose --all
  - cargo test --verbose --all
